### ISSUE TITLE
The grant type was not specified in the request

### ISSUE THREAD

**Issue by k0v4back** [hosannahighertech/yii2-oauth2-server#11]
Hello, I have one problem. When I whant to send request on this address http://api.testk0v4.xyz/oauth2/token, I have got Error 400 with code:0 and message:"The grant type was not specified in the request".
The most intresting, that on my local site all work good, but on the VDS I have this problem, and this problem appeared today.
Please, explain what the problem is, thanks.

**Comment by mtangoo** [comment]
You didn't specify which grant type you are dealing with. Can you post your json?

**Comment by k0v4back** [comment]
{"grant_type":"password", "username":"test", "password":"111111", "client_id":"testclient","client_secret":"testpass"}

**Comment by mtangoo** [comment]
How do you send it? Check if content type is set to JSON and the request is post

**Comment by k0v4back** [comment]
Thank you, I was very inattentive, I forget to write charset=UTF-8 inside Content-Type.
All in all, my header look:
**Accept: application/json
Content-Type: application/json; charset=UTF-8**

**Comment by mtangoo** [comment]
You are welcome
