### ISSUE TITLE
Yii2 2.0.13 needs changes to the Module

### ISSUE THREAD

**Issue by meyergru** [hosannahighertech/yii2-oauth2-server#2]
I had a problem when using a construct like this after the upgrade to Yii2 2.0.13:

`    	$module = Yii::$app->getModule('oauth2');
    	$response = $module->getResponse();
    	$request = $module->getRequest();

    	if (!$module->getServer()->validateAuthorizeRequest($request, $response)) {
    		Yii::$app->getResponse()->format = \yii\web\Response::FORMAT_JSON;
    		return $response->getParameters();
    	}
`

The validateAuthorizeRequest does no longer work, because $request is an instance of the wrong type.

It appears, that in Module.php, there is a test:

`   public function getServer()
    {
        if(!$this->has('server')) {
            $storages = [];
`

Which should now read:

`   public function getServer()
    {
        if(!$this->has('server', true)) {
            $storages = [];
`

This is because the Module/ServiceLocator->has() method searches upwards per default from Yii2 2.0.13 on, which can be avoided by checkInstance = true as the second parameter.

I think that the same change should be applied to the has() call in getRequest() and getRepsonse() - and also, the member names should be changed from 'server', 'request', 'response' to 'oauth2server', 'oauth2request' and 'oauth2response' in order to discriminate them from other name spaces.

**Comment by mtangoo** [comment]
hi,
Sorry. Somehow I missed this.
Can you send a PR please?

**Comment by meyergru** [comment]
Sure, here you go:

[Module.patch.txt](https://github.com/hosannahighertech/yii2-oauth2-server/files/1513529/Module.patch.txt)

**Comment by mtangoo** [comment]
merged your PR. Sorry for late reply. I didn't saw notification until today
